owner: martinbartolo
repo: bopkit-status

sites:
  - name: Bopkit Main Site
    url: https://www.bopkit.com
    icon: https://www.bopkit.com/favicon.ico
    maxResponseTime: 3000
  - name: Bopkit Robots
    url: https://www.bopkit.com/robots.txt
    icon: https://www.bopkit.com/favicon.ico
    maxResponseTime: 2000

status-website:
  cname: status.bopkit.com
  name: Bopkit Status
  logoUrl: https://www.bopkit.com/favicon.ico
  favicon: https://www.bopkit.com/favicon.ico
  introTitle: "**Bopkit** Service Status"
  introMessage: Real-time monitoring of all Bopkit services. Check here for current system status and incident history.
  theme: dark

  links:
    - rel: preconnect
      href: https://fonts.googleapis.com
    - rel: preconnect
      href: https://fonts.gstatic.com
      crossorigin: true
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700;800;900&display=swap
    - rel: stylesheet
      href: /assets/status-theme.css

  navbar:
    - title: Status
      href: /
    - title: Bopkit
      href: https://www.bopkit.com
    - title: Support
      href: https://www.bopkit.com/support

  metaTags:
    - name: description
      content: Real-time status monitoring for Bopkit services. Check here for current system status and incident history.
    - name: theme-color
      content: "#001716"
    - property: og:title
      content: Bopkit Service Status
    - property: og:description
      content: Real-time monitoring of all Bopkit services
    - property: og:url
      content: https://status.bopkit.com
    - property: og:image
      content: https://www.bopkit.com/favicon.ico
    - name: twitter:card
      content: summary_large_image
    - name: twitter:title
      content: Bopkit Service Status
    - name: twitter:description
      content: Real-time monitoring of all Bopkit services

  footer: "© 2025 Bopkit. All rights reserved."

  i18n:
    footer: "© 2025 Bopkit. All rights reserved. This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)"

assignees:
  - martinbartolo

user-agent: bopkit-status-monitor

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
