owner: martinbartolo
repo: bopkit-status

sites:
  - name: Bopkit Main Site
    url: https://www.bopkit.com
    icon: https://www.bopkit.com/favicon.ico
    maxResponseTime: 3000
  - name: Bopkit Robots
    url: https://www.bopkit.com/robots.txt
    icon: https://www.bopkit.com/favicon.ico
    maxResponseTime: 2000

status-website:
  cname: status.bopkit.com
  name: Bopkit Status
  logoUrl: https://www.bopkit.com/favicon.ico
  favicon: https://www.bopkit.com/favicon.ico
  introTitle: "**Bopkit** Service Status"
  introMessage: Real-time monitoring of all Bopkit services. Check here for current system status and incident history.
  themeUrl: /assets/status-theme.css

  links:
    - rel: preconnect
      href: https://fonts.googleapis.com
    - rel: preconnect
      href: https://fonts.gstatic.com
      crossorigin: true
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700;800;900&display=swap

  customHeadHtml: |
    <style>
      /* Force hide Upptime's default navigation - be very aggressive */
      body > div > div > nav:not([aria-label="Bopkit links"]),
      body nav:not(#bopkit-topbar):not([aria-label="Bopkit links"]),
      nav.svelte-a08hsz,
      header.svelte-a08hsz,
      nav[class*="svelte-"]:not(#bopkit-topbar),
      header[class*="svelte-"],
      nav[role="navigation"]:not(#bopkit-topbar):not([aria-label="Bopkit links"]) {
        display: none !important;
        visibility: hidden !important;
        opacity: 0 !important;
        height: 0 !important;
        overflow: hidden !important;
      }
      
      /* Also hide any links pointing to root in nav elements */
      nav a[href="/"],
      nav a[href="#"] {
        display: none !important;
      }
    </style>

  customBodyHtml: |
    <div id="bopkit-topbar" role="navigation" aria-label="Bopkit links">
      <a href="https://www.bopkit.com">Bopkit Home</a>
      <a href="https://www.bopkit.com/support">Support</a>
    </div>

  navbar: []

  metaTags:
    - name: "color-scheme"
      content: "light"
    - name: description
      content: Real-time status monitoring for Bopkit services. Check here for current system status and incident history.
    - name: theme-color
      content: "#ffffff"
    - property: og:title
      content: Bopkit Service Status
    - property: og:description
      content: Real-time monitoring of all Bopkit services
    - property: og:url
      content: https://status.bopkit.com
    - property: og:image
      content: https://www.bopkit.com/favicon.ico
    - name: twitter:card
      content: summary_large_image

assignees:
  - martinbartolo

user-agent: bopkit-status-monitor

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

i18n:
  footer: "© 2025 Bopkit. All rights reserved."
