# Repository information
owner: martinbartolo
repo: bopkit-status

# Sites to monitor (we'll use placeholder URLs for now)
sites:
  - name: Bopkit Main Site
    url: https://www.bopkit.com
    icon: https://www.bopkit.com/favicon.ico
    maxResponseTime: 3000

  - name: Bopkit Robots
    url: https://www.bopkit.com/robots.txt
    maxResponseTime: 2000

# Status website configuration
status-website:
  # Basic configuration
  baseUrl: /
  cname: status.bopkit.com
  logoUrl: https://www.bopkit.com/favicon.ico
  name: Bopkit Status
  introTitle: "**Bopkit** Service Status"
  introMessage: Real-time monitoring of all Bopkit services. Check here for current system status and incident history.

  # Theme
  theme: dark

  # Custom styling
  customHeadHtml: |
    <style>
      body { 
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      }
    </style>

  # Navigation
  navbar:
    - title: Status
      href: /
    - title: Bopkit
      href: https://www.bopkit.com
    - title: Support
      href: https://www.bopkit.com/support

  # Meta tags
  metaTags:
    - name: description
      content: Real-time status monitoring for Bopkit services
    - property: og:title
      content: Bopkit Service Status

  # Footer
  footer: © 2025 Bopkit. All rights reserved.

# Issue assignment (for email notifications)
assignees:
  - martinbartolo

# Commit messages
commitMessages:
  readmeContent: ":pencil: Update status summary"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)"
  graphsUpdate: ":bento: Update graphs [skip ci]"

# Workflow schedule
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# User agent
user-agent: bopkit-status-monitor

# Skip some updates for cleaner repo
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
