owner: martinbartolo
repo: bopkit-status

sites:
  - name: Bopkit Main Site
    url: https://www.bopkit.com
    icon: https://www.bopkit.com/favicon.ico
    maxResponseTime: 3000
  - name: Bopkit Robots
    url: https://www.bopkit.com/robots.txt
    maxResponseTime: 2000

status-website:
  baseUrl: /
  cname: status.bopkit.com
  logoUrl: https://www.bopkit.com/favicon.ico
  name: Bopkit Status
  introTitle: "**Bopkit** Service Status"
  introMessage: Real-time monitoring of all Bopkit services. Check here for current system status and incident history.
  theme: dark
  customHeadHtml: |
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

    <style>
      :root {
        /* Core palette (light) - mirrors app globals */
        --background: 0 0% 100%;
        --foreground: 222.2 84% 4.9%;
        --muted: 210 40% 96.1%;
        --muted-foreground: 215.4 16.3% 46.9%;
        --popover: 0 0% 100%;
        --popover-foreground: 222.2 84% 4.9%;
        --card: 0 0% 100%;
        --card-foreground: 222.2 84% 4.9%;
        --border: 214.3 31.8% 70.4%;
        --input: 214.3 31.8% 70.4%;
        --primary: 222.2 47.4% 11.2%;
        --primary-foreground: 210 40% 98%;
        --secondary: 210 40% 96.1%;
        --secondary-foreground: 222.2 47.4% 11.2%;
        --accent: 210 40% 96.1%;
        --accent-foreground: 222.2 47.4% 11.2%;
        --ring: 222.2 84% 4.9%;
        --radius: 0.75rem;

        /* Brand */
        --bopkit-accent: 216 100% 48%; /* #0062F5 */
        --bopkit-accent-hover: 216 100% 55%;
        --bopkit-accent-foreground: 0 0% 100%;

        /* Status colors */
        --success: 120 71% 35%;
        --success-foreground: 144 100% 97%;
        --warning: 40 95% 45%;
        --warning-foreground: 48 100% 97%;
        --destructive: 0 84.2% 60.2%;
        --destructive-foreground: 210 40% 98%;
        --info: 210 95% 45%;
        --info-foreground: 210 100% 97%;

        /* Charts (light) */
        --chart-1: 222 85% 56%;
        --chart-2: 195 75% 52%;
        --chart-3: 185 70% 58%;
        --chart-4: 25 85% 58%;
        --chart-5: 145 65% 48%;
        --chart-6: 350 70% 62%;
        --chart-7: 260 55% 60%;
        --chart-8: 220 15% 65%;

        /* Status badges mapping */
        --status-up: var(--success);
        --status-up-foreground: var(--success-foreground);
        --status-degraded: var(--warning);
        --status-degraded-foreground: var(--warning-foreground);
        --status-down: var(--destructive);
        --status-down-foreground: var(--destructive-foreground);
        --status-unknown: var(--info);
        --status-unknown-foreground: var(--info-foreground);
      }

      .dark, [data-theme="dark"] {
        --background: 222.2 84% 4.9%;
        --foreground: 210 40% 98%;
        --muted: 217.2 32.6% 17.5%;
        --muted-foreground: 215 20.2% 65.1%;
        --popover: 222.2 84% 4.9%;
        --popover-foreground: 210 40% 98%;
        --card: 222.2 84% 4.9%;
        --card-foreground: 210 40% 98%;
        --border: 217.2 32.6% 17.5%;
        --input: 217.2 32.6% 17.5%;
        --primary: 210 40% 98%;
        --primary-foreground: 222.2 47.4% 11.2%;
        --secondary: 217.2 32.6% 17.5%;
        --secondary-foreground: 210 40% 98%;
        --accent: 217.2 32.6% 17.5%;
        --accent-foreground: 210 40% 98%;
        --ring: 212.7 26.8% 83.9%;

        /* Charts (dark) */
        --chart-1: 222 85% 62%;
        --chart-2: 195 75% 58%;
        --chart-3: 185 70% 64%;
        --chart-4: 25 85% 64%;
        --chart-5: 145 65% 54%;
        --chart-6: 350 70% 68%;
        --chart-7: 260 55% 66%;
        --chart-8: 220 15% 72%;
      }

      /* Global reset + typography */
      *, *::before, *::after { box-sizing: border-box; }
      html { scroll-behavior: smooth; scroll-padding-top: 5rem; }
      body {
        font-family: 'Figtree', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', sans-serif;
        background-color: hsl(var(--background));
        color: hsl(var(--foreground));
        line-height: 1.6;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        transition: background-color 0.3s ease, color 0.3s ease;
        min-height: 100vh;
      }

      h1,h2,h3,h4,h5,h6 { color: hsl(var(--foreground)); font-weight: 800; line-height: 1.2; }
      h1 { font-size: 2.25rem; }
      h2 { font-size: 1.75rem; }
      h3 { font-size: 1.25rem; }
      p { color: hsl(var(--foreground) / 0.9); }

      a {
        color: hsl(var(--bopkit-accent));
        text-decoration: none;
        transition: color .2s ease, opacity .2s ease;
      }
      a:hover { color: hsl(var(--bopkit-accent-hover)); text-decoration: underline; }

      code, pre, kbd, samp {
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
      }
      pre, code {
        background-color: hsl(var(--muted));
        color: hsl(var(--foreground));
        border: 1px solid hsl(var(--border));
        border-radius: calc(var(--radius) - 4px);
        padding: .25rem .5rem;
      }
      pre { padding: 1rem; overflow: auto; }

      hr {
        border: none;
        border-top: 1px solid hsl(var(--border));
        margin: 1.5rem 0;
      }

      /* Focus styles */
      *:focus-visible {
        outline: 2px solid hsl(var(--ring));
        outline-offset: 2px;
      }

      /* Header */
      header {
        background-color: hsl(var(--background) / 0.95);
        border-bottom: 1px solid hsl(var(--border));
        position: sticky; top: 0; z-index: 50;
        backdrop-filter: blur(8px);
      }
      header .container {
        max-width: 1280px; margin: 0 auto; padding: 1rem 1.5rem;
        display: flex; align-items: center; justify-content: space-between; gap: 1rem; flex-wrap: wrap;
      }
      header h1 {
        font-size: 1.5rem; font-weight: 800; display: flex; align-items: center; gap: .75rem;
      }
      header img { height: 32px; width: 32px; border-radius: var(--radius); }

      /* Navbar */
      nav { display: flex; gap: .5rem; flex-wrap: wrap; }
      nav a {
        color: hsl(var(--muted-foreground));
        padding: .5rem 1rem; border-radius: calc(var(--radius) - 2px);
        font-weight: 600; font-size: .875rem; transition: all .2s ease;
        display: inline-flex; align-items: center;
      }
      nav a:hover { color: hsl(var(--foreground)); background-color: hsl(var(--accent)); }

      /* Main layout */
      main { max-width: 1280px; margin: 0 auto; padding: 2.5rem 1.5rem; min-height: calc(100vh - 200px); }

      /* Intro */
      .intro { text-align: center; margin-bottom: 3rem; }
      .intro h1 { font-size: 2.25rem; margin-bottom: .5rem; }
      .intro p { font-size: 1.05rem; color: hsl(var(--muted-foreground)); max-width: 680px; margin: 0 auto; }

      /* Cards */
      .status, .card {
        background-color: hsl(var(--card));
        color: hsl(var(--card-foreground));
        border: 1px solid hsl(var(--border));
        border-radius: var(--radius);
        padding: 1.25rem;
        box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);
        transition: box-shadow .2s ease, transform .2s ease;
      }
      .status + .status { margin-top: 1rem; }
      .status:hover, .card:hover { box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1); transform: translateY(-2px); }
      .status h2, .card h2 {
        font-size: 1.125rem; font-weight: 700; display: flex; align-items: center; gap: .75rem; margin-bottom: .5rem;
      }

      /* Badges */
      .badge {
        display: inline-flex; align-items: center; gap: .5rem;
        padding: .375rem .75rem; border-radius: calc(var(--radius) - 4px);
        font-size: .8rem; font-weight: 700; text-transform: uppercase; letter-spacing: .025em;
      }
      .badge::before { content: ""; width: 8px; height: 8px; border-radius: 50%; }
      .badge.up { background-color: hsl(var(--status-up) / 0.15); color: hsl(var(--status-up)); }
      .badge.degraded { background-color: hsl(var(--status-degraded) / 0.15); color: hsl(var(--status-degraded)); }
      .badge.down { background-color: hsl(var(--status-down) / 0.15); color: hsl(var(--status-down)); }
      .badge.unknown { background-color: hsl(var(--status-unknown) / 0.15); color: hsl(var(--status-unknown)); }

      /* Metrics grid */
      .metrics {
        display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-top: 1rem;
      }
      .metric { background-color: hsl(var(--muted)); padding: 1rem; border-radius: calc(var(--radius) - 2px); }
      .metric-label { font-size: .75rem; color: hsl(var(--muted-foreground)); font-weight: 600; letter-spacing: .03em; text-transform: uppercase; }
      .metric-value { font-size: 1.35rem; font-weight: 800; }

      /* Graph container */
      .graph { margin-top: 1rem; padding: 1rem; background-color: hsl(var(--muted) / 0.5); border-radius: calc(var(--radius) - 2px); overflow-x: auto; }
      .graph img { width: 100%; height: auto; border-radius: calc(var(--radius) - 4px); }

      /* Uptime bar */
      .uptime-bar { display: flex; height: 36px; border-radius: calc(var(--radius) - 2px); overflow: hidden; border: 1px solid hsl(var(--border)); margin-top: .75rem; }
      .uptime-day { flex: 1; transition: transform .2s ease, opacity .2s ease; }
      .uptime-day.up { background-color: hsl(var(--status-up)); }
      .uptime-day.degraded { background-color: hsl(var(--status-degraded)); }
      .uptime-day.down { background-color: hsl(var(--status-down)); }
      .uptime-day.unknown { background-color: hsl(var(--status-unknown)); }
      .uptime-day:hover { opacity: .85; transform: scaleY(1.05); }

      /* Tables (history pages) */
      table { width: 100%; border-collapse: collapse; background: hsl(var(--card)); color: hsl(var(--card-foreground)); }
      thead th {
        text-align: left; font-size: .8rem; font-weight: 700; color: hsl(var(--muted-foreground));
        border-bottom: 1px solid hsl(var(--border)); padding: .75rem 1rem; text-transform: uppercase; letter-spacing: .03em;
      }
      tbody td { padding: .75rem 1rem; border-bottom: 1px solid hsl(var(--border)); }
      tbody tr:hover { background-color: hsl(var(--accent)); }

      /* Buttons */
      button, .button, a.button {
        display: inline-flex; align-items: center; justify-content: center;
        padding: .625rem 1rem; border-radius: calc(var(--radius) - 2px);
        font-weight: 700; font-size: .875rem; cursor: pointer; text-decoration: none; border: none;
        transition: transform .1s ease, box-shadow .2s ease, background-color .2s ease, color .2s ease;
        font-family: inherit;
      }
      button:disabled, .button:disabled { opacity: .5; cursor: not-allowed; }
      .button-primary { background-color: hsl(var(--bopkit-accent)); color: hsl(var(--bopkit-accent-foreground)); }
      .button-primary:hover { background-color: hsl(var(--bopkit-accent-hover)); transform: translateY(-1px); box-shadow: 0 8px 20px -12px hsl(var(--bopkit-accent) / 0.7); }
      .button-secondary { background-color: hsl(var(--secondary)); color: hsl(var(--secondary-foreground)); border: 1px solid hsl(var(--border)); }
      .button-secondary:hover { background-color: hsl(var(--accent)); }

      /* Forms */
      input, select, textarea {
        width: 100%; background: hsl(var(--background)); color: hsl(var(--foreground));
        border: 1px solid hsl(var(--border)); border-radius: calc(var(--radius) - 2px);
        padding: .5rem .75rem; font-size: .95rem;
      }
      input::placeholder, textarea::placeholder { color: hsl(var(--muted-foreground)); }

      /* History timeline blocks */
      .history { margin-top: 1.5rem; }
      .history h3 { font-size: 1rem; font-weight: 700; margin-bottom: .75rem; }
      .history-item {
        padding: 1rem; border-left: 3px solid hsl(var(--bopkit-accent));
        background-color: hsl(var(--muted) / 0.5); border-radius: 0 calc(var(--radius) - 2px) calc(var(--radius) - 2px) 0; margin-bottom: 1rem;
      }
      .history-item time { display: block; font-size: .8rem; color: hsl(var(--muted-foreground)); margin-bottom: .35rem; font-weight: 600; }

      /* Live indicator */
      .live-indicator {
        display: inline-flex; align-items: center; gap: .5rem;
        padding: .5rem 1rem; background-color: hsl(var(--status-up) / 0.1);
        border: 1px solid hsl(var(--status-up) / 0.3); border-radius: var(--radius);
        font-size: .875rem; font-weight: 700; color: hsl(var(--status-up));
      }
      .live-indicator::before {
        content: ""; width: 10px; height: 10px; border-radius: 50%; background-color: hsl(var(--status-up));
        animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
      }

      /* Loading shimmer */
      @keyframes shimmer { 0% { background-position: -1000px 0; } 100% { background-position: 1000px 0; } }
      @keyframes pulse { 0%,100% { opacity: 1; } 50% { opacity: .5; } }
      .loading {
        animation: shimmer 2s infinite;
        background: linear-gradient(to right, hsl(var(--muted)) 0%, hsl(var(--accent)) 50%, hsl(var(--muted)) 100%);
        background-size: 1000px 100%;
      }

      /* Footer */
      footer {
        background-color: hsl(var(--card)); border-top: 1px solid hsl(var(--border));
        padding: 2rem 0; margin-top: 3rem;
      }
      footer .container { max-width: 1280px; margin: 0 auto; padding: 0 1.5rem; text-align: center; }
      footer p { color: hsl(var(--muted-foreground)); font-size: .85rem; }
      footer a { color: hsl(var(--bopkit-accent)); font-weight: 600; }
      footer a:hover { color: hsl(var(--bopkit-accent-hover)); text-decoration: underline; }

      /* Responsive */
      @media (max-width: 768px) {
        header h1 { font-size: 1.25rem; }
        .intro h1 { font-size: 1.85rem; }
        .intro p { font-size: 1rem; }
        .metrics { grid-template-columns: 1fr; }
        main { padding: 2rem 1rem; }
        nav { width: 100%; justify-content: center; }
      }

      /* Print */
      @media print {
        header, nav, footer { display: none; }
        main { max-width: 100%; padding: 0; }
        .status { break-inside: avoid; }
      }

      /* Smooth property transitions */
      * {
        transition-property: background-color, border-color, color, fill, stroke, box-shadow, transform;
        transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
        transition-duration: 150ms;
      }
    </style>

  navbar:
    - title: Status
      href: /
    - title: Bopkit
      href: https://www.bopkit.com
    - title: Support
      href: https://www.bopkit.com/support

  metaTags:
    - name: description
      content: Real-time status monitoring for Bopkit services. Check here for current system status and incident history.
    - property: og:title
      content: Bopkit Service Status
    - property: og:description
      content: Real-time monitoring of all Bopkit services
    - property: og:type
      content: website
    - property: og:image
      content: https://www.bopkit.com/favicon.ico
    - name: twitter:card
      content: summary
    - name: twitter:title
      content: Bopkit Service Status
    - name: twitter:description
      content: Real-time monitoring of all Bopkit services

  footer: "© 2025 Bopkit. All rights reserved."

assignees:
  - martinbartolo

commitMessages:
  readmeContent: ":pencil: Update status summary"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)"
  graphsUpdate: ":bento: Update graphs [skip ci]"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

user-agent: bopkit-status-monitor

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
